### ISSUE TITLE
HTML output valid?

### ISSUE THREAD

**Issue by bracke** [AdaCore/gnatdoc#26]
Hi 

When gnatdoc creates html based on the supplied template, it seems to strip all quotation marks for attribute values.
Is that a bug? Can i disable it?

**Comment by godunko** [comment]
No, it is not a bug. GNATdoc uses XHTML templates, but outputs HTML5 code. Quotation is not necessary in many cases in HTML5; quotation mark/apostrophe characters is used when necessary.

There is no options to disable it, it is valid HTML5.
