### ISSUE TITLE
Is there any intro / tutorial for how to use libgnatdoc?

### ISSUE THREAD

**Issue by bracke** [AdaCore/gnatdoc#29]

**Comment by godunko** [comment]
`libgnatdoc` is internal library to share documentation extraction code between GNATdoc and Ada Language Server.

You can look at [GNATdoc.Comments.Extractor](https://github.com/AdaCore/gnatdoc/blob/master/source/gnatdoc-comments-extractor.ads) package and [GNATdoc.Comments.Helpers](https://github.com/AdaCore/gnatdoc/blob/master/source/gnatdoc-comments-helpers.ads) packages as starting point. First is used to extract documentation, and last one contains utilities to convert extracted documentation into format compatible with LSP protocol.
